/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBoosterNFT,
  IBoosterNFTInterface,
} from "../../../contracts/interface/IBoosterNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_tokenId",
        type: "uint16",
      },
    ],
    name: "boosterInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "multiplier",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "no",
            type: "uint8",
          },
        ],
        internalType: "struct IBoosterNFT.BoosterInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_amount",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint16[]",
        name: "tokenIds",
        type: "uint16[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBoosterNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IBoosterNFTInterface {
    return new utils.Interface(_abi) as IBoosterNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBoosterNFT {
    return new Contract(address, _abi, signerOrProvider) as IBoosterNFT;
  }
}
