/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMultiplierNFT,
  IMultiplierNFTInterface,
} from "../../../contracts/interface/IMultiplierNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_multiplier",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "multipliers",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMultiplierNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IMultiplierNFTInterface {
    return new utils.Interface(_abi) as IMultiplierNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMultiplierNFT {
    return new Contract(address, _abi, signerOrProvider) as IMultiplierNFT;
  }
}
