/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IDarwinVesterInterface extends utils.Interface {
  functions: {};

  events: {
    "Claim(address,uint256)": EventFragment;
    "StakeEvoture(address,uint256,uint256)": EventFragment;
    "Vest(address,uint256)": EventFragment;
    "Withdraw(address,uint256)": EventFragment;
    "WithdrawEvoture(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeEvoture"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Vest"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawEvoture"): EventFragment;
}

export interface ClaimEventObject {
  user: string;
  claimAmount: BigNumber;
}
export type ClaimEvent = TypedEvent<[string, BigNumber], ClaimEventObject>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface StakeEvotureEventObject {
  user: string;
  evotureTokenId: BigNumber;
  multiplier: BigNumber;
}
export type StakeEvotureEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  StakeEvotureEventObject
>;

export type StakeEvotureEventFilter = TypedEventFilter<StakeEvotureEvent>;

export interface VestEventObject {
  user: string;
  vestAmount: BigNumber;
}
export type VestEvent = TypedEvent<[string, BigNumber], VestEventObject>;

export type VestEventFilter = TypedEventFilter<VestEvent>;

export interface WithdrawEventObject {
  user: string;
  withdrawAmount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface WithdrawEvotureEventObject {
  user: string;
  evotureTokenId: BigNumber;
}
export type WithdrawEvotureEvent = TypedEvent<
  [string, BigNumber],
  WithdrawEvotureEventObject
>;

export type WithdrawEvotureEventFilter = TypedEventFilter<WithdrawEvotureEvent>;

export interface IDarwinVester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDarwinVesterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "Claim(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      claimAmount?: PromiseOrValue<BigNumberish> | null
    ): ClaimEventFilter;
    Claim(
      user?: PromiseOrValue<string> | null,
      claimAmount?: PromiseOrValue<BigNumberish> | null
    ): ClaimEventFilter;

    "StakeEvoture(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      evotureTokenId?: PromiseOrValue<BigNumberish> | null,
      multiplier?: PromiseOrValue<BigNumberish> | null
    ): StakeEvotureEventFilter;
    StakeEvoture(
      user?: PromiseOrValue<string> | null,
      evotureTokenId?: PromiseOrValue<BigNumberish> | null,
      multiplier?: PromiseOrValue<BigNumberish> | null
    ): StakeEvotureEventFilter;

    "Vest(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      vestAmount?: PromiseOrValue<BigNumberish> | null
    ): VestEventFilter;
    Vest(
      user?: PromiseOrValue<string> | null,
      vestAmount?: PromiseOrValue<BigNumberish> | null
    ): VestEventFilter;

    "Withdraw(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      withdrawAmount?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;
    Withdraw(
      user?: PromiseOrValue<string> | null,
      withdrawAmount?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;

    "WithdrawEvoture(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      evotureTokenId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEvotureEventFilter;
    WithdrawEvoture(
      user?: PromiseOrValue<string> | null,
      evotureTokenId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEvotureEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
