/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IDarwinInterface extends utils.Interface {
  functions: {
    "bulkTransfer(address[],uint256[])": FunctionFragment;
    "communityPause()": FunctionFragment;
    "communityUnPause()": FunctionFragment;
    "distributeRewards(uint256)": FunctionFragment;
    "emergencyPause()": FunctionFragment;
    "emergencyUnPause()": FunctionFragment;
    "isExcludedFromHoldingLimit(address)": FunctionFragment;
    "isExcludedFromSellLimit(address)": FunctionFragment;
    "isPaused()": FunctionFragment;
    "maxTokenHoldingSize()": FunctionFragment;
    "maxTokenSellSize()": FunctionFragment;
    "mint(address,uint256)": FunctionFragment;
    "registerDarwinSwapPair(address)": FunctionFragment;
    "registerPair(address)": FunctionFragment;
    "setDarwinSwapFactory(address)": FunctionFragment;
    "setHoldingLimitWhitelist(address,bool)": FunctionFragment;
    "setLive()": FunctionFragment;
    "setMaintenance(address,bool)": FunctionFragment;
    "setMinter(address,bool)": FunctionFragment;
    "setPauseWhitelist(address,bool)": FunctionFragment;
    "setPresaleAddress(address)": FunctionFragment;
    "setReceiveRewards(address,bool)": FunctionFragment;
    "setSecurity(address,bool)": FunctionFragment;
    "setSellLimitWhitelist(address,bool)": FunctionFragment;
    "setUpgrader(address,bool)": FunctionFragment;
    "stakedDarwin()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bulkTransfer"
      | "communityPause"
      | "communityUnPause"
      | "distributeRewards"
      | "emergencyPause"
      | "emergencyUnPause"
      | "isExcludedFromHoldingLimit"
      | "isExcludedFromSellLimit"
      | "isPaused"
      | "maxTokenHoldingSize"
      | "maxTokenSellSize"
      | "mint"
      | "registerDarwinSwapPair"
      | "registerPair"
      | "setDarwinSwapFactory"
      | "setHoldingLimitWhitelist"
      | "setLive"
      | "setMaintenance"
      | "setMinter"
      | "setPauseWhitelist"
      | "setPresaleAddress"
      | "setReceiveRewards"
      | "setSecurity"
      | "setSellLimitWhitelist"
      | "setUpgrader"
      | "stakedDarwin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bulkTransfer",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "communityPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "communityUnPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isExcludedFromHoldingLimit",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isExcludedFromSellLimit",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxTokenHoldingSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTokenSellSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDarwinSwapPair",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPair",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDarwinSwapFactory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setHoldingLimitWhitelist",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(functionFragment: "setLive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaintenance",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinter",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseWhitelist",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPresaleAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiveRewards",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurity",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSellLimitWhitelist",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpgrader",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedDarwin",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bulkTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communityPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communityUnPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExcludedFromHoldingLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExcludedFromSellLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxTokenHoldingSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTokenSellSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDarwinSwapPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDarwinSwapFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHoldingLimitWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaintenance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMinter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPauseWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPresaleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiveRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSellLimitWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpgrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakedDarwin",
    data: BytesLike
  ): Result;

  events: {
    "ExcludedFromReflection(address,bool)": EventFragment;
    "ExcludedFromSellLimit(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExcludedFromReflection"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExcludedFromSellLimit"): EventFragment;
}

export interface ExcludedFromReflectionEventObject {
  account: string;
  isExcluded: boolean;
}
export type ExcludedFromReflectionEvent = TypedEvent<
  [string, boolean],
  ExcludedFromReflectionEventObject
>;

export type ExcludedFromReflectionEventFilter =
  TypedEventFilter<ExcludedFromReflectionEvent>;

export interface ExcludedFromSellLimitEventObject {
  account: string;
  isExcluded: boolean;
}
export type ExcludedFromSellLimitEvent = TypedEvent<
  [string, boolean],
  ExcludedFromSellLimitEventObject
>;

export type ExcludedFromSellLimitEventFilter =
  TypedEventFilter<ExcludedFromSellLimitEvent>;

export interface IDarwin extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDarwinInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bulkTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    communityPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    communityUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    distributeRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isExcludedFromHoldingLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExcludedFromSellLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPaused(overrides?: CallOverrides): Promise<[boolean]>;

    maxTokenHoldingSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxTokenSellSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      account: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerDarwinSwapPair(
      _pair: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerPair(
      pairAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDarwinSwapFactory(
      _darwinSwapFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setHoldingLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLive(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaintenance(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinter(
      user_: PromiseOrValue<string>,
      canMint_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPauseWhitelist(
      _addr: PromiseOrValue<string>,
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPresaleAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setReceiveRewards(
      account: PromiseOrValue<string>,
      shouldReceive: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSecurity(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSellLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUpgrader(
      _account: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakedDarwin(overrides?: CallOverrides): Promise<[string]>;
  };

  bulkTransfer(
    recipients: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  communityPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  communityUnPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  distributeRewards(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyUnPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isExcludedFromHoldingLimit(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isExcludedFromSellLimit(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isPaused(overrides?: CallOverrides): Promise<boolean>;

  maxTokenHoldingSize(overrides?: CallOverrides): Promise<BigNumber>;

  maxTokenSellSize(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    account: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerDarwinSwapPair(
    _pair: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerPair(
    pairAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDarwinSwapFactory(
    _darwinSwapFactory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setHoldingLimitWhitelist(
    account: PromiseOrValue<string>,
    whitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLive(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaintenance(
    _addr: PromiseOrValue<string>,
    _hasRole: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinter(
    user_: PromiseOrValue<string>,
    canMint_: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPauseWhitelist(
    _addr: PromiseOrValue<string>,
    value: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPresaleAddress(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setReceiveRewards(
    account: PromiseOrValue<string>,
    shouldReceive: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSecurity(
    _addr: PromiseOrValue<string>,
    _hasRole: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSellLimitWhitelist(
    account: PromiseOrValue<string>,
    whitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUpgrader(
    _account: PromiseOrValue<string>,
    _hasRole: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakedDarwin(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bulkTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    communityPause(overrides?: CallOverrides): Promise<void>;

    communityUnPause(overrides?: CallOverrides): Promise<void>;

    distributeRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyPause(overrides?: CallOverrides): Promise<void>;

    emergencyUnPause(overrides?: CallOverrides): Promise<void>;

    isExcludedFromHoldingLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExcludedFromSellLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPaused(overrides?: CallOverrides): Promise<boolean>;

    maxTokenHoldingSize(overrides?: CallOverrides): Promise<BigNumber>;

    maxTokenSellSize(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      account: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerDarwinSwapPair(
      _pair: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerPair(
      pairAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDarwinSwapFactory(
      _darwinSwapFactory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setHoldingLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLive(overrides?: CallOverrides): Promise<void>;

    setMaintenance(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinter(
      user_: PromiseOrValue<string>,
      canMint_: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPauseWhitelist(
      _addr: PromiseOrValue<string>,
      value: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPresaleAddress(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setReceiveRewards(
      account: PromiseOrValue<string>,
      shouldReceive: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSecurity(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSellLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUpgrader(
      _account: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakedDarwin(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ExcludedFromReflection(address,bool)"(
      account?: null,
      isExcluded?: null
    ): ExcludedFromReflectionEventFilter;
    ExcludedFromReflection(
      account?: null,
      isExcluded?: null
    ): ExcludedFromReflectionEventFilter;

    "ExcludedFromSellLimit(address,bool)"(
      account?: null,
      isExcluded?: null
    ): ExcludedFromSellLimitEventFilter;
    ExcludedFromSellLimit(
      account?: null,
      isExcluded?: null
    ): ExcludedFromSellLimitEventFilter;
  };

  estimateGas: {
    bulkTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    communityPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    communityUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    distributeRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isExcludedFromHoldingLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExcludedFromSellLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPaused(overrides?: CallOverrides): Promise<BigNumber>;

    maxTokenHoldingSize(overrides?: CallOverrides): Promise<BigNumber>;

    maxTokenSellSize(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      account: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerDarwinSwapPair(
      _pair: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerPair(
      pairAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDarwinSwapFactory(
      _darwinSwapFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setHoldingLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLive(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaintenance(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinter(
      user_: PromiseOrValue<string>,
      canMint_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPauseWhitelist(
      _addr: PromiseOrValue<string>,
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPresaleAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setReceiveRewards(
      account: PromiseOrValue<string>,
      shouldReceive: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSecurity(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSellLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUpgrader(
      _account: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakedDarwin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bulkTransfer(
      recipients: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    communityPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    communityUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    distributeRewards(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyUnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isExcludedFromHoldingLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExcludedFromSellLimit(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxTokenHoldingSize(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTokenSellSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      account: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerDarwinSwapPair(
      _pair: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerPair(
      pairAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDarwinSwapFactory(
      _darwinSwapFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setHoldingLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLive(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaintenance(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinter(
      user_: PromiseOrValue<string>,
      canMint_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPauseWhitelist(
      _addr: PromiseOrValue<string>,
      value: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPresaleAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setReceiveRewards(
      account: PromiseOrValue<string>,
      shouldReceive: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSecurity(
      _addr: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSellLimitWhitelist(
      account: PromiseOrValue<string>,
      whitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUpgrader(
      _account: PromiseOrValue<string>,
      _hasRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakedDarwin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
