/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DarwinCommunity__factory } from "./DarwinCommunity__factory";
export { IDarwin__factory } from "./IDarwin__factory";
