/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface DarwinBurnerInterface extends utils.Interface {
  functions: {
    "burn()": FunctionFragment;
    "burnedTokens()": FunctionFragment;
    "darwin()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "burn" | "burnedTokens" | "darwin"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "burn", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "darwin", values?: undefined): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "darwin", data: BytesLike): Result;

  events: {};
}

export interface DarwinBurner extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DarwinBurnerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    burnedTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    darwin(overrides?: CallOverrides): Promise<[string]>;
  };

  burn(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  burnedTokens(overrides?: CallOverrides): Promise<BigNumber>;

  darwin(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    burn(overrides?: CallOverrides): Promise<void>;

    burnedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    darwin(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    burn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    burnedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    darwin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    burnedTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    darwin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
